SELECT OPE.DESC_OPERACION,
	CASE WHEN DEO.PORCENTAJE_IVA = 10 THEN 
		ROUND(SUM(DEO.IMPORTE_OPERACION)) ELSE 0 END "MONTO_10",
	CASE WHEN DEO.PORCENTAJE_IVA = 10 THEN 
		ROUND(SUM(DEO.IMPORTE_IVA)) ELSE 0 END "IVA_10",
	CASE WHEN DEO.PORCENTAJE_IVA = 5 THEN 
		ROUND(SUM(DEO.IMPORTE_OPERACION)) ELSE 0 END "MONTO_5",
	CASE WHEN DEO.PORCENTAJE_IVA = 5 
		THEN ROUND(SUM(DEO.IMPORTE_IVA)) ELSE 0 END "IVA_5"
FROM D_DETALLE_OPERACIONES DEO
JOIN D_MOVIMIENTO_OPERACIONES MOV ON DEO.ID_OPERACION = MOV.ID_OPERACION
JOIN D_OPERACIONES OPE ON OPE.COD_OPERACION = MOV.COD_OPERACION
WHERE MOV.ESTADO = 'A' AND mov.COD_OPERACION = 1
GROUP BY OPE.DESC_OPERACION, DEO.PORCENTAJE_IVA
UNION
SELECT OPE.DESC_OPERACION,
	ROUND(SUM(CASE WHEN PRO.COD_TIPO_IVA = 1 THEN 
		DEO.IMPORTE_OPERACION ELSE 0 END)) AS MONTO_10,
	ROUND(SUM(CASE WHEN PRO.COD_TIPO_IVA = 1 THEN 
		DEO.IMPORTE_OPERACION / 11 ELSE 0 END)) AS IVA_10,
	ROUND(SUM(CASE WHEN PRO.COD_TIPO_IVA = 2 THEN 
		DEO.IMPORTE_OPERACION ELSE 0 END)) AS MONTO_5,
	ROUND(SUM(CASE WHEN PRO.COD_TIPO_IVA = 2 THEN 
		DEO.IMPORTE_OPERACION / 21 ELSE 0 END)) AS IVA_5
FROM D_DETALLE_OPERACIONES DEO
JOIN D_MOVIMIENTO_OPERACIONES MOV ON DEO.ID_OPERACION = MOV.ID_OPERACION
JOIN D_OPERACIONES OPE ON OPE.COD_OPERACION = MOV.COD_OPERACION
JOIN D_DETALLE_OPERACIONES DET ON DET.ID_OPERACION = MOV.ID_OPERACION
JOIN D_PRODUCTOS PRO ON PRO.ID_PRODUCTO = DET.ID_PRODUCTO
JOIN D_TIPO_IVA tii ON tii.COD_TIPO_IVA = PRO.COD_TIPO_IVA
WHERE MOV.ESTADO = 'A' AND MOV.COD_OPERACION = 2
GROUP BY OPE.DESC_OPERACION;
