INSERT ALL
	WHEN TIPO = 'C' THEN 
		INTO D_CUENTAS_CONTABLES (CODIGO_CTA, NOMBRE_CTA, ID_TIPO, NIVEL, ORDEN, IMPUTABLE, FECHA_APERTURA, CODIGO_CTA_PADRE)
		VALUES (CODIGO_CTA, NOMBRE, ID_TIPO, NIVEL_SECUENCIA, ORDEN, IMPUTABLE_ACTIVA, FECHA_APERTURA, CODIGO_CTA_PADRE)
	WHEN TIPO = 'P' THEN
		INTO D_PLANTILLA_ASIENTO (ID_PLANTILLA, NOMBRE, ACTIVA)
		VALUES (ID_TIPO, NOMBRE, IMPUTABLE_ACTIVA)
	WHEN TIPO = 'Z' THEN
		INTO D_PLANTILLA_DETALLE (ID_PLANTILLA, SECUENCIA, DEBE_HABER, CODIGO_CTA, CATEGORIA)
		VALUES (ID_TIPO, NIVEL_SECUENCIA, ORDEN, CODIGO_CTA, CATEGORIA)
SELECT CODIGO_CTA, NOMBRE, ID_TIPO, NIVEL_SECUENCIA, ORDEN, IMPUTABLE_ACTIVA, FECHA_APERTURA, CODIGO_CTA_PADRE, TIPO, CATEGORIA
FROM CONTAB;