CREATE VIEW V_PARA_PROMO AS
WITH FORMA_PAGO_EP AS (
		SELECT COD_FORMA_PAGO, PORCENTAJE_DESCUENTO / 100 AS PORCENTAJE_DESCUENTO 
		FROM D_FORMA_PAGO WHERE DESC_FORMA_PAGO LIKE 'EFECTIVO PROMO'),
	 PROD_NO_VENDIDOS AS (
		SELECT PRO.ID_PRODUCTO FROM D_PRODUCTOS PRO
			MINUS
		SELECT ID_PRODUCTO
		FROM D_DETALLE_OPERACIONES DET
		JOIN D_MOVIMIENTO_OPERACIONES MOV ON MOV.ID_OPERACION = DET.ID_OPERACION
		WHERE MONTHS_BETWEEN(SYSDATE, MOV.FECHA_OPERACION) <= 6 AND DET.ID_OPERACION = 1
						)
SELECT
	PRO.ID_PRODUCTO,
	TPR.DESC_TIPO_PRODUCTO AS TIPO_PRODUCTO,
	PRO.DESC_PRODUCTO AS DESCRIPCION_PRODUCTO,
	PRO.PRECIO_ULTIMA_COMPRA + (PRO.PRECIO_ULTIMA_COMPRA * PRO.PORCENTAJE_BENEFICIO / 100) - (PRO.PRECIO_ULTIMA_COMPRA * (SELECT PORCENTAJE_DESCUENTO FROM FORMA_PAGO_EP)) AS PRECIO_VENTA,
	MED.DESC_MEDIDA AS UNIDAD_MEDIDA,
	(SELECT COD_FORMA_PAGO FROM FORMA_PAGO_EP) AS FORMA_PAGO
FROM D_PRODUCTOS PRO
JOIN D_TIPO_PRODUCTO TPR ON TPR.COD_TIPO_PRODUCTO = PRO.COD_TIPO_PRODUCTO
JOIN D_MEDIDA MED ON MED.COD_MEDIDA = PRO.COD_MEDIDA
WHERE PRO.ID_PRODUCTO IN (SELECT ID_PRODUCTO FROM PROD_NO_VENDIDOS)
ORDER BY PRECIO_VENTA ASC;
